Feature/1012
memonac/memonac-client pull request #13
Opened 2022-02-09 19:55 UTC by KongWooJeong

# [1012] {feature: 메모룸 상세 페이지 UI 작업 및 메모 및 프로필 렌더링}

## 노션 칸반 링크
​
- [메모룸 상세](https://www.notion.so/vanillacoding/front-61b3a3d6c4bf41908c9e8922f7658ba2)
​
## 카드에서 구현 혹은 해결하려는 내용
- DB에서 가져온 각 메모룸에 해당되는 메모 및 참여자 프로필 렌더링
- 전반적인 UI 디자인
- 뒤로가기 버튼 클릭시 전역 상태에 존재하는 현재 메모룸 정보 초기화
​
## 기타 사항
- 메모 렌더링시 해당 스크린 화면 영역이 벗어나면 화면에 스크롤이 생겨 해당 문제 논의 필요
- 실시간 채팅 부분 UI 요소만 작업 // 내부 채팅 내용 추후 실시간 채팅 부분 Task에서 진행 예정

2022-02-09 23:51 UTC, leesssuin approved these changes
우정님! css 때문에 힘들어하셨는데 너무너무 고생하셨습니다! 👍🏻👍🏻

2022-02-09 23:51 UTC, leesssuin commented on src/features/memoroom/memoRoomSaga.js
> +    yield put(getMemoListFailure(err.message));
뭔가 memoroom보다 memolist가 더 알아보기 쉽고 우리가 코드 칠때도 헷갈리지 않고 좋을것 같아요 👍🏻

2022-02-09 23:51 UTC, leesssuin commented on src/features/memoroom/memoRoomSlice.js
> +    participants: [],
participants data가 
```   
 const userInfo = {};
 userInfo[userId] = {
   name: user.name,
   email: user.email,
 };
  ```
  이런식으로 들어가는데 보내주는 저 userinfo 구조를 좀 바꾸는게 더 편할까요? 우정님은 어떻게 생각하시나요?

2022-02-10 05:28 UTC, okcorn requested changes
우정님 정말로 고생 많으셨습니다:)

2022-02-10 05:28 UTC, okcorn commented on src/components/Memo.js
> +`;
이게 prop이 있어서 될지는 모르겠으나, 별도 파일로 구분해서 작성하면 좋을 것 같습니다 !

2022-02-10 05:28 UTC, okcorn commented on src/components/Profile.js
> +    background: #999;
hexcode 6자리로 넣어주세요 !

2022-02-10 05:28 UTC, okcorn commented on src/features/memoroom/MemoRoom.js
> +      </div>
div 태그로 많이 감싸주신 이유가 따로 있을까요 ??

2022-02-10 05:28 UTC, okcorn commented on src/components/Memo.js
> +    background-color: "#ffffff";
```suggestion
    background-color: #ffffff;
```

2022-02-10 05:28 UTC, okcorn commented on src/components/Memo.js
> +  function handleTextChange({ target }) {
어떤 text인지 정확하게 명시해주면 좋을 것 같습니다  
```suggestion
  function handleMemoTextChange({ target }) {
```

2022-02-10 05:28 UTC, okcorn commented on src/components/Profile.js
> +  p {
p 라는 일반 태그가 아닌 클래스명을 지정해서 수정해도 좋을 것 같습니다.

2022-02-10 05:28 UTC, okcorn commented on src/features/memoroom/MemoRoom.js
> +          <Button text="share" color="#3E497A" width={100} />
버튼 컴포넌트의 color 속성을 잘 이용해주셨네요 ㅎㅎ

2022-02-10 05:28 UTC, okcorn commented on src/features/memoroom/memoRoomSaga.js
> +    const memoRoomData = yield call(memoApi.getMemoList, userId, memoroomId);
```suggestion
    const memoRoomData = yield call(memoApi.getMemoList, { userId, memoroomId });
```  
이렇게 한번에 묶어줘도 좋을 것 같아요!

2022-02-10 06:10 UTC, KongWooJeong commented on src/features/memoroom/memoRoomSaga.js
> +    const memoRoomData = yield call(memoApi.getMemoList, userId, memoroomId);
말씀주신 방법이 더 좋은것 같아요!! 바로 수정할게요!!

2022-02-10 06:10 UTC, KongWooJeong commented on src/features/memoroom/memoRoomSaga.js
> +    yield put(getMemoListFailure(err.message));
해당 부분 수정 완료 하였습니다!!

2022-02-10 06:10 UTC, KongWooJeong commented on src/features/memoroom/memoRoomSlice.js
> +    participants: [],
그럼 이부분에 대하여 회의 진행후 결정 하시는걸로 하시죠!!

2022-02-10 06:39 UTC, okcorn approved these changes
우정님, 반영된 부분 확인하였습니다.

2022-02-10 06:40 UTC, leesssuin commented on src/features/memoroom/memoRoomSlice.js
> +    participants: [],
네네!

2022-02-10 06:43 UTC, okcorn commented on src/features/memoroom/MemoRoom.js
> +`;
네네 !@

2022-02-10 06:57 UTC, merged